version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SERVER_ADDRESS=http://localhost:5000
  backend:
    container_name: backend
    restart: on-failure
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017
      - JWT_SECRET=secret
      - JWT_EXPIRATION=1800000
      - JWT_COOKIE_NAME=womanup_token
    build:
      context: ./backend
    depends_on:
      - mongo
    ports:
      - "5000:5000"
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - "8083:8081"
