/** Declaration file generated by dts-gen */

export = react_responsive_canvas;

declare class react_responsive_canvas {
  constructor(...args: any[]);

  componentDidMount(): void;

  componentWillUnmount(): void;

  render(): any;

  static defaultProps: {
    scale: number;
  };
}
