FROM node:12-alpine as build
WORKDIR /app
COPY . ./
RUN npm install
RUN npm run build

ARG REACT_APP_SERVER_ADRESS
ARG REACT_APP_LOGIN_PATH
ARG REACT_APP_REGISTER_PATH
ARG REACT_APP_STATISTICS_PATH
ARG REACT_APP_SQUEEZE_PATH
ARG REACT_APP_LINKS_PER_LIST

ENV REACT_APP_SERVER_ADRESS=$REACT_APP_SERVER_ADRESS
ENV REACT_APP_LOGIN_PATH=$REACT_APP_LOGIN_PATH
ENV REACT_APP_REGISTER_PATH=$REACT_APP_REGISTER_PATH
ENV REACT_APP_STATISTICS_PATH=$REACT_APP_STATISTICS_PATH
ENV REACT_APP_SQUEEZE_PATH=$REACT_APP_SQUEEZE_PATH
ENV REACT_APP_LINKS_PER_LIST=$REACT_APP_LINKS_PER_LIST

FROM nginx:1.16.0-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]