// @ts-nocheck ибо warehouseList как с апи wb
import { Warehouse } from "../entities/wb/warehouse";
export const warehouseList: Warehouse[] = [
    {
        boxDeliveryAndStorageExpr: "115",
        boxDeliveryBase: "40,25",
        boxDeliveryLiter: "9,78",
        boxStorageBase: "-",
        boxStorageLiter: "-",
        warehouseName: "Маркетплейс",
    },
    {
        boxDeliveryAndStorageExpr: "180",
        boxDeliveryBase: "63",
        boxDeliveryLiter: "15,3",
        boxStorageBase: "0,1",
        boxStorageLiter: "0,1",
        warehouseName: "Коледино",
    },
    {
        boxDeliveryAndStorageExpr: "200",
        boxDeliveryBase: "70",
        boxDeliveryLiter: "17",
        boxStorageBase: "0,12",
        boxStorageLiter: "0,12",
        warehouseName: "Подольск",
    },
    {
        boxDeliveryAndStorageExpr: "125",
        boxDeliveryBase: "43,75",
        boxDeliveryLiter: "10,63",
        boxStorageBase: "0,09",
        boxStorageLiter: "0,09",
        warehouseName: "Подольск 4",
    },
    {
        boxDeliveryAndStorageExpr: "145",
        boxDeliveryBase: "50,75",
        boxDeliveryLiter: "12,33",
        boxStorageBase: "0,08",
        boxStorageLiter: "0,08",
        warehouseName: "Электросталь",
    },
    {
        boxDeliveryAndStorageExpr: "145",
        boxDeliveryBase: "50,75",
        boxDeliveryLiter: "12,33",
        boxStorageBase: "0,08",
        boxStorageLiter: "0,08",
        warehouseName: "Тула",
    },
    {
        boxDeliveryAndStorageExpr: "200",
        boxDeliveryBase: "70",
        boxDeliveryLiter: "17",
        boxStorageBase: "0,11",
        boxStorageLiter: "0,11",
        warehouseName: "Чехов 2",
    },
    {
        boxDeliveryAndStorageExpr: "195",
        boxDeliveryBase: "68,25",
        boxDeliveryLiter: "16,58",
        boxStorageBase: "0,13",
        boxStorageLiter: "0,13",
        warehouseName: "Белая дача",
    },
    {
        boxDeliveryAndStorageExpr: "280",
        boxDeliveryBase: "98",
        boxDeliveryLiter: "23,8",
        boxStorageBase: "0,2",
        boxStorageLiter: "0,2",
        warehouseName: "Белые Столбы",
    },
    {
        boxDeliveryAndStorageExpr: "95",
        boxDeliveryBase: "33,25",
        boxDeliveryLiter: "8,08",
        boxStorageBase: "0,07",
        boxStorageLiter: "0,07",
        warehouseName: "Радумля СГТ",
    },
    {
        boxDeliveryAndStorageExpr: "140",
        boxDeliveryBase: "49",
        boxDeliveryLiter: "11,9",
        boxStorageBase: "0,1",
        boxStorageLiter: "0,1",
        warehouseName: "Рязань (Тюшевское)",
    },
    {
        boxDeliveryAndStorageExpr: "180",
        boxDeliveryBase: "63",
        boxDeliveryLiter: "15,3",
        boxStorageBase: "0,13",
        boxStorageLiter: "0,13",
        warehouseName: "Котовск",
    },
    {
        boxDeliveryAndStorageExpr: "75",
        boxDeliveryBase: "26,25",
        boxDeliveryLiter: "6,38",
        boxStorageBase: "0,05",
        boxStorageLiter: "0,05",
        warehouseName: "Обухово СГТ",
    },
    {
        boxDeliveryAndStorageExpr: "75",
        boxDeliveryBase: "26,25",
        boxDeliveryLiter: "6,38",
        boxStorageBase: "0,05",
        boxStorageLiter: "0,05",
        warehouseName: "Голицыно СГТ",
    },
    {
        boxDeliveryAndStorageExpr: "130",
        boxDeliveryBase: "45,5",
        boxDeliveryLiter: "11,05",
        boxStorageBase: "0,09",
        boxStorageLiter: "0,09",
        warehouseName: "Сабурово",
    },
    {
        boxDeliveryAndStorageExpr: "140",
        boxDeliveryBase: "49",
        boxDeliveryLiter: "11,9",
        boxStorageBase: "0,1",
        boxStorageLiter: "0,1",
        warehouseName: "Владимир",
    },
    {
        boxDeliveryAndStorageExpr: "190",
        boxDeliveryBase: "66,5",
        boxDeliveryLiter: "16,15",
        boxStorageBase: "0,13",
        boxStorageLiter: "0,13",
        warehouseName: "Щербинка",
    },
    {
        boxDeliveryAndStorageExpr: "230",
        boxDeliveryBase: "80,5",
        boxDeliveryLiter: "19,55",
        boxStorageBase: "0,14",
        boxStorageLiter: "0,14",
        warehouseName: "Санкт-Петербург Уткина Заводь",
    },
    {
        boxDeliveryAndStorageExpr: "95",
        boxDeliveryBase: "33,25",
        boxDeliveryLiter: "8,08",
        boxStorageBase: "0,07",
        boxStorageLiter: "0,07",
        warehouseName: "Шушары СГТ",
    },
    {
        boxDeliveryAndStorageExpr: "150",
        boxDeliveryBase: "52,5",
        boxDeliveryLiter: "12,75",
        boxStorageBase: "0,1",
        boxStorageLiter: "0,1",
        warehouseName: "Краснодар",
    },
    {
        boxDeliveryAndStorageExpr: "150",
        boxDeliveryBase: "52,5",
        boxDeliveryLiter: "12,75",
        boxStorageBase: "0,09",
        boxStorageLiter: "0,09",
        warehouseName: "Невинномысск",
    },
    {
        boxDeliveryAndStorageExpr: "195",
        boxDeliveryBase: "68,25",
        boxDeliveryLiter: "16,58",
        boxStorageBase: "0,13",
        boxStorageLiter: "0,13",
        warehouseName: "Казань",
    },
    {
        boxDeliveryAndStorageExpr: "200",
        boxDeliveryBase: "70",
        boxDeliveryLiter: "17",
        boxStorageBase: "0,13",
        boxStorageLiter: "0,13",
        warehouseName: "Екатеринбург - Испытателей 14г",
    },
    {
        boxDeliveryAndStorageExpr: "150",
        boxDeliveryBase: "52,5",
        boxDeliveryLiter: "12,75",
        boxStorageBase: "0",
        boxStorageLiter: "0",
        warehouseName: "Екатеринбург - Перспективный 12",
    },
    {
        boxDeliveryAndStorageExpr: "445",
        boxDeliveryBase: "155,75",
        boxDeliveryLiter: "37,83",
        boxStorageBase: "0,29",
        boxStorageLiter: "0,29",
        warehouseName: "Новосибирск",
    },
    {
        boxDeliveryAndStorageExpr: "220",
        boxDeliveryBase: "77",
        boxDeliveryLiter: "18,7",
        boxStorageBase: "0,14",
        boxStorageLiter: "0,14",
        warehouseName: "Хабаровск",
    },
    {
        boxDeliveryAndStorageExpr: "125",
        boxDeliveryBase: "43,75",
        boxDeliveryLiter: "10,63",
        boxStorageBase: "0,08",
        boxStorageLiter: "0,08",
        warehouseName: "Атакент",
    },
    {
        boxDeliveryAndStorageExpr: "145",
        boxDeliveryBase: "50,75",
        boxDeliveryLiter: "12,33",
        boxStorageBase: "0,1",
        boxStorageLiter: "0,1",
        warehouseName: "Астана Карагандинское шоссе",
    },
];
export const warehouseListMock: Warehouse[] = Array.from({ length: 20 }, (_, i) => ({
    boxDeliveryAndStorageExpr: i + 100,
    boxDeliveryBase: i + 50,
    boxDeliveryLiter: i + 25,
    boxStorageBase: i + 60,
    boxStorageLiter: i + 30,
    warehouseName: `Warehouse ${i}`,
}));
